import TOML from '@iarna/toml'

export const CODEX_MANAGED_MCP_BEGIN = '# BEGIN agents-sync managed MCP'
export const CODEX_MANAGED_MCP_END = '# END agents-sync managed MCP'
const LEGACY_GENERATED_HEADER = '# Generated by agents sync. Do not edit manually.'

type TomlLexState = 'normal' | 'basic' | 'literal' | 'multilineBasic' | 'multilineLiteral'

interface StandaloneCommentLine {
  start: number
  contentEnd: number
}

interface TomlLine {
  start: number
  contentEnd: number
  end: number
}

/**
 * Merge generated MCP tables into a Codex project config without rewriting
 * project-owned settings. Agent Sync owns only the text between its markers.
 */
export function mergeCodexConfig(existingContent: string, generatedContent: string): string {
  validateToml(existingContent, 'existing Codex TOML')
  validateToml(generatedContent, 'generated Codex TOML')

  const beginLines = findStandaloneCommentLines(existingContent, CODEX_MANAGED_MCP_BEGIN)
  const endLines = findStandaloneCommentLines(existingContent, CODEX_MANAGED_MCP_END)
  const beginLine = beginLines[0]
  const endLine = endLines[0]

  if (
    beginLines.length > 1
    || endLines.length > 1
    || (beginLine === undefined) !== (endLine === undefined)
    || (beginLine !== undefined && endLine !== undefined && endLine.start < beginLine.start)
  ) {
    throw new Error('Invalid existing Codex TOML: malformed agents-sync managed MCP block')
  }

  const lineEnding = existingContent.includes('\r\n') ? '\r\n' : '\n'
  const normalizedGenerated = generatedContent.trimEnd().replace(/\r\n|\n/g, lineEnding)
  const managedBlock = [
    CODEX_MANAGED_MCP_BEGIN,
    normalizedGenerated,
    CODEX_MANAGED_MCP_END
  ].join(lineEnding)

  let merged: string
  if (beginLine !== undefined && endLine !== undefined) {
    merged = [
      existingContent.slice(0, beginLine.start),
      managedBlock,
      existingContent.slice(endLine.contentEnd)
    ].join('')
  } else if (existingContent.length === 0) {
    merged = `${managedBlock}${lineEnding}`
  } else if (isLegacyGeneratedCodexConfig(existingContent)) {
    const preserved = removeLegacyGeneratedCodexMcp(existingContent)
    const separator = preserved.length === 0 || preserved.endsWith('\n') ? '' : lineEnding
    merged = `${preserved}${separator}${managedBlock}${lineEnding}`
  } else {
    const separator = existingContent.endsWith('\n') ? '' : lineEnding
    merged = `${existingContent}${separator}${managedBlock}${lineEnding}`
  }

  validateToml(merged, 'merged Codex TOML')
  return merged
}

/** Remove this project's managed MCP block while preserving surrounding TOML. */
export function removeCodexManagedBlock(existingContent: string): string {
  validateToml(existingContent, 'existing Codex TOML')

  const beginLines = findStandaloneCommentLines(existingContent, CODEX_MANAGED_MCP_BEGIN)
  const endLines = findStandaloneCommentLines(existingContent, CODEX_MANAGED_MCP_END)
  const beginLine = beginLines[0]
  const endLine = endLines[0]

  if (beginLine === undefined && endLine === undefined) return existingContent
  if (
    beginLines.length > 1
    || endLines.length > 1
    || beginLine === undefined
    || endLine === undefined
    || endLine.start < beginLine.start
  ) {
    throw new Error('Invalid existing Codex TOML: malformed agents-sync managed MCP block')
  }

  const cleaned = `${existingContent.slice(0, beginLine.start)}${existingContent.slice(endLine.contentEnd)}`
  validateToml(cleaned, 'cleaned Codex TOML')
  return cleaned
}

/** Return whether content contains the legacy fully-generated Codex header. */
export function isLegacyGeneratedCodexConfig(content: string): boolean {
  return findStandaloneCommentLines(content, LEGACY_GENERATED_HEADER).length === 1
}

/** Remove MCP tables from the legacy fully-generated Codex file while preserving other TOML sections. */
export function removeLegacyGeneratedCodexMcp(content: string): string {
  const lines = getTomlLines(content)
  const tableHeaders = findTableHeaderLines(content, lines)
  const mcpHeaders = tableHeaders.filter((line) => isMcpTableHeader(content.slice(line.start, line.contentEnd)))
  const legacyHeaders = findStandaloneCommentLines(content, LEGACY_GENERATED_HEADER)
  const ranges: Array<{ start: number; end: number }> = legacyHeaders.map((line) => ({
    start: line.start,
    end: getLineEnd(lines, line.start, line.contentEnd)
  }))

  for (const header of mcpHeaders) {
    const nextHeader = tableHeaders.find((candidate) => candidate.start > header.start)
    ranges.push({
      start: header.start,
      end: nextHeader?.start ?? content.length
    })
  }

  if (ranges.length === 0) return content

  ranges.sort((left, right) => left.start - right.start)
  const mergedRanges: Array<{ start: number; end: number }> = []
  for (const range of ranges) {
    const previous = mergedRanges.at(-1)
    if (previous && range.start <= previous.end) {
      previous.end = Math.max(previous.end, range.end)
    } else {
      mergedRanges.push({ ...range })
    }
  }

  let result = ''
  let cursor = 0
  for (const range of mergedRanges) {
    result += content.slice(cursor, range.start)
    cursor = range.end
  }
  return result + content.slice(cursor)
}

/** Split TOML into source-position-aware lines. */
function getTomlLines(content: string): TomlLine[] {
  const lines: TomlLine[] = []
  let lineStart = 0

  while (lineStart < content.length || (content.length === 0 && lines.length === 0)) {
    const newlineIndex = content.indexOf('\n', lineStart)
    const lineBreakStart = newlineIndex >= 0 ? newlineIndex : content.length
    const contentEnd = lineBreakStart > lineStart && content[lineBreakStart - 1] === '\r'
      ? lineBreakStart - 1
      : lineBreakStart
    const end = newlineIndex >= 0 ? newlineIndex + 1 : content.length
    lines.push({ start: lineStart, contentEnd, end })
    if (newlineIndex < 0) break
    lineStart = newlineIndex + 1
  }

  return lines
}

/** Return the full line end for a known line start. */
function getLineEnd(lines: TomlLine[], start: number, fallback: number): number {
  return lines.find((line) => line.start === start)?.end ?? fallback
}

/** Locate top-level TOML table headers outside multiline strings. */
function findTableHeaderLines(content: string, lines: TomlLine[]): TomlLine[] {
  const headers: TomlLine[] = []
  let state: TomlLexState = 'normal'

  for (const line of lines) {
    if (state === 'normal' && isTableHeader(content.slice(line.start, line.contentEnd))) {
      headers.push(line)
    }
    state = scanTomlLine(content, line.start, line.contentEnd, state)
  }

  return headers
}

/** Return whether a line contains only a valid TOML table header and optional comment. */
function isTableHeader(line: string): boolean {
  const trimmed = stripTrailingTomlComment(line).trim()
  if (!trimmed.startsWith('[')) return false
  if (trimmed.startsWith('[[') ? !trimmed.endsWith(']]') : !trimmed.endsWith(']')) return false
  try {
    TOML.parse(trimmed)
    return true
  } catch {
    return false
  }
}

/** Return whether a TOML table header belongs to the MCP namespace. */
function isMcpTableHeader(line: string): boolean {
  const trimmed = stripTrailingTomlComment(line).trim()
  return /^\[{1,2}\s*mcp_servers(?:\s*\]|\.)/u.test(trimmed)
}

/** Strip a TOML comment that begins outside quoted strings. */
function stripTrailingTomlComment(line: string): string {
  let state: 'normal' | 'basic' | 'literal' = 'normal'
  for (let index = 0; index < line.length; index += 1) {
    const character = line[index]
    if (state === 'normal') {
      if (character === '#') return line.slice(0, index)
      if (character === '"') state = 'basic'
      if (character === "'") state = 'literal'
      continue
    }
    if (state === 'basic') {
      if (character === '\\') {
        index += 1
      } else if (character === '"') {
        state = 'normal'
      }
      continue
    }
    if (character === "'") state = 'normal'
  }
  return line
}

/** Locate exact standalone marker comments outside TOML strings. */
function findStandaloneCommentLines(content: string, marker: string): StandaloneCommentLine[] {
  const matches: StandaloneCommentLine[] = []
  let state: TomlLexState = 'normal'
  let lineStart = 0

  while (lineStart <= content.length) {
    const newlineIndex = content.indexOf('\n', lineStart)
    const lineBreakStart = newlineIndex >= 0 ? newlineIndex : content.length
    const contentEnd = lineBreakStart > lineStart && content[lineBreakStart - 1] === '\r'
      ? lineBreakStart - 1
      : lineBreakStart

    if (state === 'normal' && content.slice(lineStart, contentEnd) === marker) {
      matches.push({ start: lineStart, contentEnd })
    }

    state = scanTomlLine(content, lineStart, contentEnd, state)
    if (newlineIndex < 0) break
    lineStart = newlineIndex + 1
  }

  return matches
}

/** Advance TOML string lexical state across one line. */
function scanTomlLine(
  content: string,
  start: number,
  end: number,
  initialState: TomlLexState,
): TomlLexState {
  let state = initialState
  let index = start

  while (index < end) {
    if (state === 'normal') {
      if (content[index] === '#') break
      if (content.startsWith('"""', index)) {
        state = 'multilineBasic'
        index += 3
        continue
      }
      if (content.startsWith("'''", index)) {
        state = 'multilineLiteral'
        index += 3
        continue
      }
      if (content[index] === '"') state = 'basic'
      if (content[index] === "'") state = 'literal'
      index += 1
      continue
    }

    if (state === 'basic') {
      if (content[index] === '\\') {
        index += 2
        continue
      }
      if (content[index] === '"') state = 'normal'
      index += 1
      continue
    }

    if (state === 'literal') {
      if (content[index] === "'") state = 'normal'
      index += 1
      continue
    }

    if (state === 'multilineBasic') {
      if (content[index] === '\\') {
        index += 2
        continue
      }
      if (content.startsWith('"""', index)) {
        index = consumeQuoteRun(content, index, end, '"')
        state = 'normal'
        continue
      }
      index += 1
      continue
    }

    if (content.startsWith("'''", index)) {
      index = consumeQuoteRun(content, index, end, "'")
      state = 'normal'
      continue
    }
    index += 1
  }

  return state
}

/** Consume a contiguous run of matching quote characters. */
function consumeQuoteRun(content: string, start: number, end: number, quote: '"' | "'"): number {
  let index = start
  while (index < end && content[index] === quote) index += 1
  return index
}

/** Parse TOML and attach a contextual label to syntax failures. */
function validateToml(content: string, label: string): void {
  if (content.trim().length === 0) return

  try {
    TOML.parse(content)
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error)
    throw new Error(`Invalid ${label}: ${message}`)
  }
}
