import type { ResolvedMcpServer } from '../types.js'
import { toManagedClaudeDesktopName } from './claudeDesktop.js'

function escapeToml(value: string): string {
  return value.replaceAll('\\', '\\\\').replaceAll('"', '\\"')
}

function quoteTomlKey(key: string): string {
  return `"${escapeToml(key)}"`
}

export interface RenderResult {
  content: string
  warnings: string[]
}

export function renderCodexToml(servers: ResolvedMcpServer[]): RenderResult {
  const warnings: string[] = []
  const lines: string[] = ['# Generated by agents sync. Do not edit manually.', '']

  for (const server of servers) {
    lines.push(`[mcp_servers.${quoteTomlKey(server.name)}]`)

    if (server.transport === 'stdio') {
      if (!server.command) {
        warnings.push(`Server "${server.name}" has no command; skipped in Codex output.`)
        lines.pop()
        continue
      }
      lines.push(`command = "${escapeToml(server.command)}"`)
      lines.push(
        `args = [${(server.args ?? []).map((arg) => `"${escapeToml(arg)}"`).join(', ')}]`,
      )
      if (server.cwd) {
        lines.push(`cwd = "${escapeToml(server.cwd)}"`)
      }
    } else {
      if (!server.url) {
        warnings.push(`Server "${server.name}" has no url; skipped in Codex output.`)
        lines.pop()
        continue
      }
      if (server.transport === 'sse') {
        warnings.push(`Server "${server.name}" uses legacy sse transport; rendering as URL for Codex compatibility.`)
      }
      lines.push(`url = "${escapeToml(server.url)}"`)
    }

    lines.push('enabled = true')
    lines.push('autoApprove = []')
    lines.push('')

    if (server.env && Object.keys(server.env).length > 0) {
      lines.push(`[mcp_servers.${quoteTomlKey(server.name)}.env]`)
      for (const key of Object.keys(server.env).sort()) {
        lines.push(`${quoteTomlKey(key)} = "${escapeToml(server.env[key])}"`)
      }
      lines.push('')
    }

    if (server.headers && Object.keys(server.headers).length > 0) {
      lines.push(`[mcp_servers.${quoteTomlKey(server.name)}.http_headers]`)
      for (const key of Object.keys(server.headers).sort()) {
        lines.push(`${quoteTomlKey(key)} = "${escapeToml(server.headers[key])}"`)
      }
      lines.push('')
    }
  }

  return {
    content: `${lines.join('\n')}\n`,
    warnings
  }
}

export function renderGeminiServers(servers: ResolvedMcpServer[]): {
  mcpServers: Record<string, unknown>
  warnings: string[]
} {
  const warnings: string[] = []
  const out: Record<string, unknown> = {}

  for (const server of servers) {
    if (server.transport === 'stdio') {
      if (!server.command) {
        warnings.push(`Server "${server.name}" has no command; skipped in Gemini output.`)
        continue
      }
      out[server.name] = {
        type: 'stdio',
        command: server.command,
        args: server.args ?? [],
        ...(server.cwd ? { cwd: server.cwd } : {}),
        ...(server.env ? { env: server.env } : {})
      }
      continue
    }

    if (!server.url) {
      warnings.push(`Server "${server.name}" has no url; skipped in Gemini output.`)
      continue
    }
    out[server.name] = {
      ...(server.transport === 'http'
        ? { httpUrl: server.url }
        : { url: server.url }),
      ...(server.headers ? { headers: server.headers } : {})
    }
  }

  return { mcpServers: out, warnings }
}

/**
 * Builds a VS Code MCP servers map from a list of resolved MCP servers.
 *
 * @param servers - The resolved MCP servers to render
 * @returns An object with:
 * - `servers`: a mapping from server name to its VS Code MCP configuration. For `stdio` servers the entry contains `type: 'stdio'`, `command`, `args` (array), and optional `cwd` and `env`. For non-stdio servers the entry contains `type` (transport), `url`, and optional `headers`.
 * - `warnings`: an array of warnings for servers that were skipped or adjusted during rendering
 */
export function renderVscodeMcp(servers: ResolvedMcpServer[]): {
  servers: Record<string, unknown>
  warnings: string[]
} {
  const warnings: string[] = []
  const out: Record<string, unknown> = {}

  for (const server of servers) {
    if (server.transport === 'stdio') {
      if (!server.command) {
        warnings.push(`Server "${server.name}" has no command; skipped in VS Code MCP output.`)
        continue
      }
      out[server.name] = {
        type: 'stdio',
        command: server.command,
        args: server.args ?? [],
        ...(server.cwd ? { cwd: server.cwd } : {}),
        ...(server.env ? { env: server.env } : {})
      }
      continue
    }

    if (!server.url) {
      warnings.push(`Server "${server.name}" has no url; skipped in VS Code MCP output.`)
      continue
    }
    out[server.name] = {
      type: server.transport,
      url: server.url,
      ...(server.headers ? { headers: server.headers } : {})
    }
  }

  return { servers: out, warnings }
}

/**
 * Produce an Antigravity-compatible mapping of MCP servers and collect conversion warnings.
 *
 * @param servers - Array of resolved MCP server entries to convert
 * @returns An object with `mcpServers` (mapping server name -> Antigravity entry) and `warnings` (messages about skipped or adjusted servers).
 * `mcpServers` entries:
 * - For `transport === 'stdio'`: `{ command, args, cwd? , env? }`
 * - For non-stdio transports: `{ serverUrl, headers? }`
 * `warnings` includes notices for servers skipped due to missing `command` or `url`, and a note when legacy `sse` transports are rendered as `serverUrl`.
 */
export function renderAntigravityMcp(servers: ResolvedMcpServer[]): {
  mcpServers: Record<string, unknown>
  warnings: string[]
} {
  const warnings: string[] = []
  const out: Record<string, unknown> = {}

  for (const server of servers) {
    if (server.transport === 'stdio') {
      if (!server.command) {
        warnings.push(`Server "${server.name}" has no command; skipped in Antigravity output.`)
        continue
      }
      out[server.name] = {
        command: server.command,
        args: server.args ?? [],
        ...(server.cwd ? { cwd: server.cwd } : {}),
        ...(server.env ? { env: server.env } : {})
      }
      continue
    }

    if (!server.url) {
      warnings.push(`Server "${server.name}" has no url; skipped in Antigravity output.`)
      continue
    }
    if (server.transport === 'sse') {
      warnings.push(`Server "${server.name}" uses legacy sse transport; rendering as serverUrl for Antigravity compatibility.`)
    }
    out[server.name] = {
      serverUrl: server.url,
      ...(server.headers ? { headers: server.headers } : {})
    }
  }

  return { mcpServers: out, warnings }
}

/**
 * Render Copilot CLI's project MCP config.
 *
 * @param servers Resolved MCP servers from the shared registry.
 * @returns A Copilot CLI `mcpServers` map plus warnings for skipped entries.
 * Stdio servers without commands and remote servers without URLs are omitted.
 */
export function renderCopilotCliMcp(servers: ResolvedMcpServer[]): {
  mcpServers: Record<string, unknown>
  warnings: string[]
} {
  const warnings: string[] = []
  const out: Record<string, unknown> = {}

  for (const server of servers) {
    if (server.transport === 'stdio') {
      if (!server.command) {
        warnings.push(`Server "${server.name}" has no command; skipped in Copilot CLI MCP output.`)
        continue
      }
      out[server.name] = {
        type: 'stdio',
        command: server.command,
        args: server.args ?? [],
        tools: ['*'],
        ...(server.cwd ? { cwd: server.cwd } : {}),
        ...(server.env ? { env: server.env } : {})
      }
      continue
    }

    if (!server.url) {
      warnings.push(`Server "${server.name}" has no url; skipped in Copilot CLI MCP output.`)
      continue
    }
    out[server.name] = {
      type: server.transport,
      url: server.url,
      tools: ['*'],
      ...(server.headers ? { headers: server.headers } : {})
    }
  }

  return { mcpServers: out, warnings }
}

/**
 * Render Claude Desktop's local JSON config. Claude Desktop remote MCP servers
 * are account/UI-managed connectors, so only local stdio servers are emitted.
 */
export function renderClaudeDesktopMcp(servers: ResolvedMcpServer[], projectRoot: string): {
  mcpServers: Record<string, unknown>
  warnings: string[]
} {
  const warnings: string[] = []
  const out: Record<string, unknown> = {}

  for (const server of servers) {
    const name = toManagedClaudeDesktopName(projectRoot, server.name)
    if (server.transport === 'stdio') {
      if (!server.command) {
        warnings.push(`Server "${server.name}" has no command; skipped in Claude Desktop output.`)
        continue
      }
      out[name] = {
        type: 'stdio',
        command: server.command,
        args: server.args ?? [],
        ...(server.env ? { env: server.env } : {})
      }
      if (server.cwd) {
        warnings.push(
          `Server "${server.name}" sets cwd, but Claude Desktop claude_desktop_config.json does not document cwd support; prefer absolute paths in command/args/env.`,
        )
      }
    } else {
      warnings.push(
        `Server "${server.name}" uses ${server.transport} transport; skipped in Claude Desktop output. Remote MCP servers are managed as Claude custom connectors, not in claude_desktop_config.json.`,
      )
    }
  }

  return {
    mcpServers: out,
    warnings
  }
}

export function renderWindsurfMcp(servers: ResolvedMcpServer[]): {
  mcpServers: Record<string, unknown>
  warnings: string[]
} {
  const warnings: string[] = []
  const out: Record<string, unknown> = {}

  for (const server of servers) {
    if (server.transport === 'stdio') {
      if (!server.command) {
        warnings.push(`Server "${server.name}" has no command; skipped in Windsurf output.`)
        continue
      }
      out[server.name] = {
        command: server.command,
        args: server.args ?? [],
        ...(server.cwd ? { cwd: server.cwd } : {}),
        ...(server.env ? { env: server.env } : {})
      }
      continue
    }

    if (!server.url) {
      warnings.push(`Server "${server.name}" has no url; skipped in Windsurf output.`)
      continue
    }
    out[server.name] = {
      serverUrl: server.url,
      ...(server.headers ? { headers: server.headers } : {})
    }
  }

  return { mcpServers: out, warnings }
}

export function renderOpencodeMcp(servers: ResolvedMcpServer[]): {
  mcp: Record<string, unknown>
  warnings: string[]
} {
  const warnings: string[] = []
  const out: Record<string, unknown> = {}

  for (const server of servers) {
    if (server.transport === 'stdio') {
      if (!server.command) {
        warnings.push(`Server "${server.name}" has no command; skipped in OpenCode output.`)
        continue
      }
      out[server.name] = {
        type: 'local',
        enabled: true,
        command: [server.command, ...(server.args ?? [])],
        ...(server.cwd ? { cwd: server.cwd } : {}),
        ...(server.env ? { environment: server.env } : {})
      }
      continue
    }

    if (!server.url) {
      warnings.push(`Server "${server.name}" has no url; skipped in OpenCode output.`)
      continue
    }
    out[server.name] = {
      type: 'remote',
      enabled: true,
      url: server.url,
      ...(server.headers ? { headers: server.headers } : {})
    }
  }

  return { mcp: out, warnings }
}

export function renderJunieMcp(servers: ResolvedMcpServer[]): {
  mcpServers: Record<string, unknown>
  warnings: string[]
} {
  const warnings: string[] = []
  const out: Record<string, unknown> = {}

  for (const server of servers) {
    if (server.transport === 'stdio') {
      if (!server.command) {
        warnings.push(`Server "${server.name}" has no command; skipped in Junie output.`)
        continue
      }
      out[server.name] = {
        command: server.command,
        args: server.args ?? [],
        ...(server.cwd ? { cwd: server.cwd } : {}),
        ...(server.env ? { env: server.env } : {})
      }
      continue
    }

    if (!server.url) {
      warnings.push(`Server "${server.name}" has no url; skipped in Junie output.`)
      continue
    }
    out[server.name] = {
      url: server.url,
      ...(server.headers ? { headers: server.headers } : {})
    }
  }

  return { mcpServers: out, warnings }
}
